version: "2"

services:
  eureka-server:
    build: ../netflixbluemix-core/eurekaserver/docker
    image: registry.ng.bluemix.net/${NAMESPACE}/spring-eureka-server:latest
    expose:
     - "8080"
    mem_limit: 256

  eureka-server-dr:
    build: ../netflixbluemix-core/eurekaserverdr/docker
    image: registry.ng.bluemix.net/${NAMESPACE}/spring-eureka-server-dr:latest
    links:
     - eureka-server:eureka-server
    expose:
     - "8080"
    mem_limit: 256

  zuul-proxy:
    build: ../netflixbluemix-core/zuulproxy/docker
    image: registry.ng.bluemix.net/${NAMESPACE}/spring-zuul-proxy:latest
    links:
     - eureka-server:eureka-server
    expose:
     - "8080"
    mem_limit: 256

  nginx:
    build: ../netflixbluemix-core/nginx
    image: registry.ng.bluemix.net/${NAMESPACE}/noss-nginx:latest
    links:
     - eureka-server:eureka-server
     - eureka-server-dr:eureka-server-dr
     - zuul-proxy:zuul-proxy
    ports:
     - "80:80"
    mem_limit: 256

  db2-hello-service:
    build: ../netflixbluemix-db2/db2microservice/docker
    image: registry.ng.bluemix.net/${NAMESPACE}/db2-hello-service:latest
    links:
     - eureka-server:eureka-server
    expose:
     - "8080"
    mem_limit: 256

  mq-hello-service:
    build: ../netflixbluemix-mq/mqmicroservice/docker
    image: registry.ng.bluemix.net/${NAMESPACE}/mq-hello-service:latest
    links:
     - eureka-server:eureka-server
    expose:
     - "8080"
    mem_limit: 256

  mysql-hello-service:
   build: ../netflixbluemix-mysql/microservice/docker
   image: registry.ng.bluemix.net/${NAMESPACE}/mysql-hello-service
   links:
     - eureka-server:eureka-server
   expose:
     - "8080"
   mem_limit: 256

  elasticsearch-server:
    image: registry.ng.bluemix.net/${NAMESPACE}/elasticsearch:1.7.3
    expose:
     - "9200"
     - "9300"
    mem_limit: 256

  elasticsearch-service:
   build: ../netflixbluemix-elasticsearch/elasticsearchservice/docker
   image: registry.ng.bluemix.net/${NAMESPACE}/elasticsearch-service
   links:
     - eureka-server:eureka-server
     - eureka-server-dr:eureka-server-dr
     - elasticsearch-server:elasticsearch-server
   expose:
     - "8080"
   mem_limit: 256
